//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotifySecurity.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NotifySecurity.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer from wordphish server:.
        /// </summary>
        internal static string AnswerFromSwordphish {
            get {
                return ResourceManager.GetString("AnswerFromSwordphish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Security.
        /// </summary>
        internal static string ButtonLabel {
            get {
                return ResourceManager.GetString("ButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Security.
        /// </summary>
        internal static string ContextMenuLabel {
            get {
                return ResourceManager.GetString("ContextMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Business phone:.
        /// </summary>
        internal static string EmailBody_BusinessPhone {
            get {
                return ResourceManager.GetString("EmailBody_BusinessPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Computername:.
        /// </summary>
        internal static string EmailBody_Computername {
            get {
                return ResourceManager.GetString("EmailBody_Computername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Department:.
        /// </summary>
        internal static string EmailBody_Department {
            get {
                return ResourceManager.GetString("EmailBody_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, I received the attached email and I think it is suspicious.
        /// </summary>
        internal static string EmailBody_line1 {
            get {
                return ResourceManager.GetString("EmailBody_line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I think this mail is malicious for the following reasons:.
        /// </summary>
        internal static string EmailBody_line2 {
            get {
                return ResourceManager.GetString("EmailBody_line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please analyze and provide some feedback..
        /// </summary>
        internal static string EmailBody_line3 {
            get {
                return ResourceManager.GetString("EmailBody_line3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Location:.
        /// </summary>
        internal static string EmailBody_Location {
            get {
                return ResourceManager.GetString("EmailBody_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Mobile phone:.
        /// </summary>
        internal static string EmailBody_MobilePhone {
            get {
                return ResourceManager.GetString("EmailBody_MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message headers.
        /// </summary>
        internal static string EmailBody_msgHeader {
            get {
                return ResourceManager.GetString("EmailBody_msgHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possibly useful information:.
        /// </summary>
        internal static string EmailBody_PossiblyUsefulIInformation {
            get {
                return ResourceManager.GetString("EmailBody_PossiblyUsefulIInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - STMP address:.
        /// </summary>
        internal static string EmailBody_STMPAddress {
            get {
                return ResourceManager.GetString("EmailBody_STMPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Title:.
        /// </summary>
        internal static string EmailBody_Title {
            get {
                return ResourceManager.GetString("EmailBody_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Name:.
        /// </summary>
        internal static string EmailBody_Username {
            get {
                return ResourceManager.GetString("EmailBody_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Windows username:.
        /// </summary>
        internal static string EmailBody_WindowsUsername {
            get {
                return ResourceManager.GetString("EmailBody_WindowsUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Please add here why this email looks suspect&gt;.
        /// </summary>
        internal static string EmailBody_YourReason {
            get {
                return ResourceManager.GetString("EmailBody_YourReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [User Alert] Suspicious mail.
        /// </summary>
        internal static string EmailSubject {
            get {
                return ResourceManager.GetString("EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security addin error.
        /// </summary>
        internal static string ErrorSubject {
            get {
                return ResourceManager.GetString("ErrorSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured, please notify your security contact and give him/her the following information: .
        /// </summary>
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Outlook item was not a mail, no header extracted.
        /// </summary>
        internal static string ItemNotMail {
            get {
                return ResourceManager.GetString("ItemNotMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad luck... this case has not been identified by the dev.
        /// </summary>
        internal static string MsgBadLuck {
            get {
                return ResourceManager.GetString("MsgBadLuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shieldy - Alert Security.
        /// </summary>
        internal static string MsgBox_Title {
            get {
                return ResourceManager.GetString("MsgBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well done, you&apos;ve well identified our fake mail generated for the phishing campain !.
        /// </summary>
        internal static string MsgIfSwordphishDetected {
            get {
                return ResourceManager.GetString("MsgIfSwordphishDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one mail..
        /// </summary>
        internal static string MsgSelectOneMail {
            get {
                return ResourceManager.GetString("MsgSelectOneMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select only one mail to be raised to the security team..
        /// </summary>
        internal static string MsgSelectOnlyOneMail {
            get {
                return ResourceManager.GetString("MsgSelectOnlyOneMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO ANSWER from Swordphish server.
        /// </summary>
        internal static string NoAnswerFromSwordphish {
            get {
                return ResourceManager.GetString("NoAnswerFromSwordphish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no header found.
        /// </summary>
        internal static string NoHeaderFound {
            get {
                return ResourceManager.GetString("NoHeaderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Security.
        /// </summary>
        internal static string ScreentipLabel {
            get {
                return ResourceManager.GetString("ScreentipLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shieldy {
            get {
                object obj = ResourceManager.GetObject("shieldy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Security.
        /// </summary>
        internal static string TabLabel {
            get {
                return ResourceManager.GetString("TabLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using default template.
        /// </summary>
        internal static string UsingDefaultTemplate {
            get {
                return ResourceManager.GetString("UsingDefaultTemplate", resourceCulture);
            }
        }
    }
}
